### ISSUE TITLE
Problem with matplotlib

### ISSUE THREAD

**Issue by ivanteokh** [fraser-lab/EMRinger#1]
Was able to run emringer.py just fine, and generated a .pkl file. But when I tried running emringer_score.py, I get the following error:

ImportError: dlopen(/Applications/PHENIX-1.9-1692/Contents/phenix-1.9-1692/build/mac-intel-osx-x86_64/base/Python.framework/Versions/Current/lib/python2.7/site-packages/matplotlib-1.3.0-py2.7-macosx-10.4-x86_64.egg/matplotlib/ft2font.so, 2): Library not loaded: /scratch/phenix/phenix-1.9-1692/build/mac-intel-osx-x86_64/base/lib/libfreetype.6.dylib
  Referenced from: /Applications/PHENIX-1.9-1692/Contents/phenix-1.9-1692/build/mac-intel-osx-x86_64/base/Python.framework/Versions/Current/lib/python2.7/site-packages/matplotlib-1.3.0-py2.7-macosx-10.4-x86_64.egg/matplotlib/ft2font.so
  Reason: image not found

Then I made a test script with just the line "import matplotlib.pyplot as plt", and it generated the same error when run through phenix.python.

**Comment by bbarad** [comment]
This is apparently a problem with your installation of phenix, based on the error you get with your test script. Your installation is on the old side; would you mind trying with one of the more recent nightlies? You can also use phenix.emringer in the command line with the most recent nightlies to generate scores, although the rolling window analysis is not fully implemented.

**Comment by ivanteokh** [comment]
Thank you, that fixed the problem.
