### ISSUE TITLE
Negative RSCC values for PHEs, TYRs

### ISSUE THREAD

**Issue by wenchang-zhou-roivant** [fraser-lab/EMRinger#2]
I installed cctbx and want to get the RSCC for all residues in my protein, I run `libtbx.python em_rscc.py model.pdb model.map`, but when I check the result, many sidechains fit into the density very well but got negative RSCC values. Should I tune some of the settings inside the em_rscc.py? Thanks!

**Comment by bbarad** [comment]
Can you run the command with the --test flag to see if the script is running properly? I haven't touched this script in a good number of years (I think I ran it on 1.13 or 1.14) and cctbx has changed dramatically in the way it handles maps and models (for the better!) in the intervening time.

**Comment by bbarad** [comment]
There is a more modern/supported version of this in `phenix.validation_cryoem` if you are using phenix instead of the open source cctbx.

**Comment by wenchang-zhou-roivant** [comment]
Thanks @bbarad, just find out that phenix.real_space_correlation will also do that. BTW, I'm working with crystal structures and electron density.

**Comment by bbarad** [comment]
Whoops, sorry for the assumption! Glad you found a working tool!
